# Generated by Django 5.2.4 on 2025-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('status', models.JSONField()),
                ('diagnostics', models.JSONField()),
                ('location', models.JSONField()),
            ],
        ),
    ]
